/*
 * LamsToolService.java
 *
 * Created on 11 January 2005, 13:49
 */

package org.lamsfoundation.lams.tool.service;


import org.lamsfoundation.lams.learningdesign.Activity;
import org.lamsfoundation.lams.learningdesign.ToolActivity;
import org.lamsfoundation.lams.lesson.Lesson;
import org.lamsfoundation.lams.tool.ToolSession;
import org.lamsfoundation.lams.usermanagement.User;

/**
 * This interface defines the service that lams tool package offers to other
 * lams core modules, such as, lams_learning, lams_authoring, lams_monitoring.
 * 
 * @author Jacky Fang
 * @since  2005-3-17
 * @version
 */
public interface ILamsCoreToolService
{
    /**
     * Creates a Lams ToolSession for a learner and activity.
     * @param learner
     * @param activity
     */
    public ToolSession createToolSession(User learner, ToolActivity activity,Lesson lesson) throws LamsToolServiceException;
    
    
    /**
     * Returns the previously created ToolSession for a learner and activity.
     */
    public ToolSession getToolSessionByLearner(User learner, Activity activity) throws LamsToolServiceException;
    
    /**
     * Returns the tool session according to tool session id.
     * @param toolSessionId the requested tool session id.
     * @return the tool session object
     */
    public ToolSession getToolSessionById(Long toolSessionId);
    
    /**
     * Get the lams tool session based on activity and learner.
     * @param learner
     * @param toolActivity
     * @return
     * @throws LamsToolServiceException
     */
    public ToolSession getToolSessionByActivity(User learner, ToolActivity toolActivity)throws LamsToolServiceException;
    /**
     * Notify tools to create their tool sessions in their own tables. 
     * @param toolSessionId the tool session generated by lams.
     * @param activity the activity correspondent to that tool session.
     */
    public void notifyToolsToCreateSession(Long toolSessionId, ToolActivity activity);
    
    public Long copyToolContent(ToolActivity toolActivity);
    
    public void updateToolSession(ToolSession toolSession);

}
