SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lasbmt11_session;
DROP TABLE IF EXISTS tl_lasbmt11_report;
DROP TABLE IF EXISTS tl_lasbmt11_submission_details;
DROP TABLE IF EXISTS tl_lasbmt11_content;
SET FOREIGN_KEY_CHECKS=1;