-- Turn off autocommit, so nothing is committed if there is an error
SET AUTOCOMMIT = 0;
SET FOREIGN_KEY_CHECKS=0;
----------------------Put all sql statements below here-------------------------

-- LDEV-3640 Add necessary cascades

ALTER TABLE tl_lasurv11_option DROP FOREIGN KEY FK85AB46F26966134F;
ALTER TABLE tl_lasurv11_option ADD CONSTRAINT FK85AB46F26966134F FOREIGN KEY (`question_uid`)
REFERENCES `tl_lasurv11_question` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE tl_lasurv11_question DROP FOREIGN KEY FK872D4F23D14146E5;
ALTER TABLE tl_lasurv11_question ADD CONSTRAINT FK872D4F23D14146E5 FOREIGN KEY (`survey_uid`)
REFERENCES `tl_lasurv11_survey` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tl_lasurv11_question DROP FOREIGN KEY FK872D4F23E4C99A5F;
ALTER TABLE tl_lasurv11_question ADD CONSTRAINT FK872D4F23E4C99A5F FOREIGN KEY (`create_by`)
REFERENCES `tl_lasurv11_user` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE tl_lasurv11_session DROP FOREIGN KEY FKF08793B9D14146E5;
ALTER TABLE tl_lasurv11_session ADD CONSTRAINT FKF08793B9D14146E5 FOREIGN KEY (`survey_uid`)
REFERENCES `tl_lasurv11_survey` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE tl_lasurv11_survey DROP FOREIGN KEY FK8CC465D7E4C99A5F;
ALTER TABLE tl_lasurv11_survey ADD CONSTRAINT FK8CC465D7E4C99A5F FOREIGN KEY (`create_by`)
REFERENCES `tl_lasurv11_user` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE;


ALTER TABLE tl_lasurv11_user DROP FOREIGN KEY FK633F25884F803F63;
ALTER TABLE tl_lasurv11_user ADD CONSTRAINT FK633F25884F803F63 FOREIGN KEY (`session_uid`)
REFERENCES `tl_lasurv11_session` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tl_lasurv11_user DROP FOREIGN KEY FK633F2588D14146E5;
ALTER TABLE tl_lasurv11_user ADD CONSTRAINT FK633F2588D14146E5 FOREIGN KEY (`survey_uid`)
REFERENCES `tl_lasurv11_survey` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;
							 

ALTER TABLE tl_lasurv11_answer DROP FOREIGN KEY FK6DAAFE3BB1423DC1;
ALTER TABLE tl_lasurv11_answer ADD CONSTRAINT FK6DAAFE3BB1423DC1 FOREIGN KEY (`user_uid`)
REFERENCES `tl_lasurv11_user` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE tl_lasurv11_answer DROP FOREIGN KEY FK6DAAFE3B25F3BB77;
ALTER TABLE tl_lasurv11_answer ADD CONSTRAINT FK6DAAFE3B25F3BB77 FOREIGN KEY (`question_uid`)
REFERENCES `tl_lasurv11_question` (`uid`) ON DELETE CASCADE ON UPDATE CASCADE;

----------------------Put all sql statements above here-------------------------

-- If there were no errors, commit and restore autocommit to on
COMMIT;
SET AUTOCOMMIT = 1;
SET FOREIGN_KEY_CHECKS=1;