
 
INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
admin_url
)
VALUES
(
'lagmap10',
'gmapService',
'Gmap',
'Gmap',
'gmap',
'@tool_version@',
0,
1,
'tool/lagmap10/learning.do?mode=learner',
'tool/lagmap10/learning.do?mode=author',
'tool/lagmap10/learning.do?mode=teacher',
'tool/lagmap10/authoring.do',
'tool/lagmap10/monitoring.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lagmap10',
'org.lamsfoundation.lams.tool.gmap.ApplicationResources',
NOW(),
NOW(),
'tool/lagmap10/lagmap10admin.do'
)
