-- LDEV-1511
ALTER TABLE lams_configuration ENGINE=InnoDB;
ALTER TABLE lams_notebook_entry ENGINE=InnoDB;
ALTER TABLE lams_qtz_BLOB_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_CALENDARS ENGINE=InnoDB;
ALTER TABLE lams_qtz_CRON_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_FIRED_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_JOB_DETAILS ENGINE=InnoDB;
ALTER TABLE lams_qtz_JOB_LISTENERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_LOCKS ENGINE=InnoDB;
ALTER TABLE lams_qtz_PAUSED_TRIGGER_GRPS ENGINE=InnoDB;
ALTER TABLE lams_qtz_SCHEDULER_STATE ENGINE=InnoDB;
ALTER TABLE lams_qtz_SIMPLE_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_TRIGGER_LISTENERS ENGINE=InnoDB;
