INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lasurv11',
'lasurvSurveyService',
'Survey',
'Survey',
'survey',
'@tool_version@',
0,
2,
'tool/lasurv11/learning/start.do?mode=learner',
'tool/lasurv11/learning/start.do?mode=author',
'tool/lasurv11/learning/start.do?mode=teacher',
'tool/lasurv11/authoring/start.do',
'tool/lasurv11/monitoring/summary.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lasurv11',
'org.lamsfoundation.lams.tool.survey.ApplicationResources',
NOW(),
NOW(),
1
)