SET FOREIGN_KEY_CHECKS=0;
drop table if exists tl_latask10_condition;
drop table if exists tl_latask10_condition_tl_item;
drop table if exists tl_latask10_tasklist;
drop table if exists tl_latask10_tasklist_item;
drop table if exists tl_latask10_item_log;
drop table if exists tl_latask10_item_attachment;
drop table if exists tl_latask10_item_comment;
drop table if exists tl_latask10_session;
drop table if exists tl_latask10_user;
SET FOREIGN_KEY_CHECKS=1;