INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'latask10',
'lataskTaskListService',
'Shared TaskList',
'Shared TaskList',
'sharedtaskList',
'@tool_version@',
0,
2,
'tool/latask10/learning/start.do?mode=learner',
'tool/latask10/learning/start.do?mode=author',
'tool/latask10/learning/start.do?mode=teacher',
'tool/latask10/authoring/start.do',
'tool/latask10/monitoring/summary.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/latask10',
'org.lamsfoundation.lams.tool.taskList.ApplicationResources',
NOW(),
NOW(),
1
)