INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'laddim10',
'dimdimService',
'Dimdim',
'Dimdim',
'dimdim',
'@tool_version@',
0,
2,
'tool/laddim10/learning.do?mode=learner',
'tool/laddim10/learning.do?mode=author',
'tool/laddim10/learning.do?mode=teacher',
'tool/laddim10/authoring.do',
'tool/laddim10/monitoring.do',
'org.lamsfoundation.lams.tool.dimdim.ApplicationResources',
NOW(),
NOW(),
0
)
