
 
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lascrb11_user;
DROP TABLE IF EXISTS tl_lascrb11_attachment;
DROP TABLE IF EXISTS tl_lascrb11_session;
DROP TABLE IF EXISTS tl_lascrb11_scribe;
SET FOREIGN_KEY_CHECKS=1;





