INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
admin_url,
supports_outputs
)
VALUES
(
'laimag10',
'laimagImageGalleryService',
'ImageGallery',
'ImageGallery',
'imageGallery',
'@tool_version@',
0,
2,
'tool/laimag10/learning/start.do?mode=learner',
'tool/laimag10/learning/start.do?mode=author',
'tool/laimag10/learning/start.do?mode=teacher',
'tool/laimag10/authoring/start.do',
'tool/laimag10/monitoring/summary.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/laimag10',
'org.lamsfoundation.lams.tool.imageGallery.ApplicationResources',
NOW(),
NOW(),
'tool/laimag10/laimag10admin/start.do',
1
)