#!/bin/sh -e

. /usr/share/debconf/confmodule

db_input critical lams2/db_root_pass || true
#db_input critical lams2/db_name || true
#db_input critical lams2/db_user || true
#db_input critical lams2/db_pass || true
db_input critical lams2/server_host || true
db_input critical lams2/server_port || true
db_input critical lams2/sysadmin_user || true
db_input critical lams2/sysadmin_pass || true

db_go
