-- LDEV-1511
SET foreign_key_checks=0;

ALTER TABLE lams_configuration ENGINE=InnoDB;
ALTER TABLE lams_notebook_entry ENGINE=InnoDB;
ALTER TABLE lams_qtz_BLOB_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_CALENDARS ENGINE=InnoDB;
ALTER TABLE lams_qtz_CRON_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_FIRED_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_JOB_DETAILS ENGINE=InnoDB;
ALTER TABLE lams_qtz_JOB_LISTENERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_LOCKS ENGINE=InnoDB;
ALTER TABLE lams_qtz_PAUSED_TRIGGER_GRPS ENGINE=InnoDB;
ALTER TABLE lams_qtz_SCHEDULER_STATE ENGINE=InnoDB;
ALTER TABLE lams_qtz_SIMPLE_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_TRIGGERS ENGINE=InnoDB;
ALTER TABLE lams_qtz_TRIGGER_LISTENERS ENGINE=InnoDB;

ALTER TABLE tl_lantbk11_attachment ADD CONSTRAINT FK12090F57FC940906 FOREIGN KEY (notebook_uid) REFERENCES tl_lantbk11_notebook (uid);

ALTER TABLE tl_lantbk11_session ADD CONSTRAINT FKB7C198E2FC940906 FOREIGN KEY (notebook_uid) REFERENCES tl_lantbk11_notebook (uid);

ALTER TABLE tl_lantbk11_user ADD CONSTRAINT FKCB8A58FFA3B0FADF FOREIGN KEY (notebook_session_uid) REFERENCES tl_lantbk11_session (uid);

ALTER TABLE lams_qtz_JOB_LISTENERS ADD FOREIGN KEY (JOB_NAME,JOB_GROUP)
        REFERENCES lams_qtz_JOB_DETAILS (JOB_NAME,JOB_GROUP);
        
ALTER TABLE lams_qtz_TRIGGERS ADD FOREIGN KEY (JOB_NAME,JOB_GROUP)
        REFERENCES lams_qtz_JOB_DETAILS (JOB_NAME,JOB_GROUP);

ALTER TABLE lams_qtz_SIMPLE_TRIGGERS ADD FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES lams_qtz_TRIGGERS (TRIGGER_NAME,TRIGGER_GROUP);

ALTER TABLE lams_qtz_CRON_TRIGGERS ADD FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES lams_qtz_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP);

ALTER TABLE lams_qtz_BLOB_TRIGGERS ADD FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES lams_qtz_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP);
        
ALTER TABLE lams_qtz_TRIGGER_LISTENERS ADD FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES lams_qtz_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP);

SET foreign_key_checks=1;