<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="Messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Lamstwo Tool">
		<style type="text/css">
			@import url("/sakai-lamstwo-tool/css/Lamstwo.css");
		</style>

		<h:form id="addItem">
			<sakai:tool_bar>
				<sakai:tool_bar_item value="#{msgs.lamstwo_new}" action="#{LamstwoBean.processActionNew}" rendered="#{LamstwoBean.canCreateItem}"/>
			</sakai:tool_bar>
		</h:form>
		
		<sakai:view_content>
			<h:form id="items">
			 	<sakai:view_title value="#{msgs.lamstwo_title} Items"/>

				<sakai:messages />
				
				<sakai:instruction_message value="Hello, #{LamstwoBean.currentUserDisplayName}"/>
			
			 	<h:dataTable
			 		id="itemlist"
			 		value="#{LamstwoBean.allItems}"
			 		var="entry"
			 		columnClasses="firstColumn,secondColumn,thirdColumn,fourthColumn,fifthColumn,sixthColumn,seventhColumn"
			 		headerClass="headerAlignment"
			 		styleClass="listHier lines nolines">

					<h:column>
						<f:facet name="header">
							<h:outputText value=""/>
						</f:facet>
						<h:selectBooleanCheckbox id="itemSelect" value="#{entry.selected}" rendered="#{entry.canDelete}"/>
						<h:outputText value="" rendered="#{not entry.canDelete}"/>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.lamstwo_text}"/>
						</f:facet>
						<h:commandLink id="openLearnerLink" action="#{LamstwoBean.processActionLearner}" target="_blank">
							<h:outputText value="#{entry.item.title}"/>
						</h:commandLink>
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.lamstwo_introduction}" />
						</f:facet>
						<h:outputText value="#{entry.item.introduction}" />
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:outputText value=""/>
						</f:facet>
						<h:commandLink id="updateLink" action="#{LamstwoBean.processActionUpdate}" rendered="#{entry.canDelete}">
							<h:outputText value="#{msgs.lamstwo_edit}"/>
						</h:commandLink>						
					</h:column>
					
					<h:column>
						<f:facet name="header">
							<h:outputText value=""/>
						</f:facet>
						<h:commandLink id="openMonitorLink" action="#{LamstwoBean.processActionMonitor}" rendered="#{entry.canDelete}" target="_blank">
							<h:outputText value="#{msgs.lamstwo_monitor}"/>
						</h:commandLink>
					</h:column>
				
					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.lamstwo_hidden}"/>
						</f:facet>
						<h:selectBooleanCheckbox id="itemHidden" value="#{entry.item.hidden}" disabled="true" />
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.lamstwo_date}"/>
						</f:facet>
						<h:outputText value="#{entry.item.dateCreated}">
							<f:convertDateTime type="both" dateStyle="medium" timeStyle="short" />
						</h:outputText>
					</h:column>

				</h:dataTable>

				<sakai:button_bar rendered="#{LamstwoBean.canCreateItem}">
					<sakai:button_bar_item id="deleteItem" action="#{LamstwoBean.processActionDelete}" value="#{msgs.lamstwo_delete}"/>  
                </sakai:button_bar>

			 </h:form>
  		</sakai:view_content>	
	</sakai:view_container>
</f:view> 
