<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="Messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Lamstwo Tool" >

	<f:verbatim>
	<script type="text/javascript"> 
		var options = "location=0,toolbar=0,menubar=0,statusbar=0,width=796,height=570,resizable";
		
		function loadLearner() {
			window.location = "</f:verbatim><h:outputText value="#{LamstwoBean.learnerURL}" escape="false" /><f:verbatim>";
		}
		loadLearner();
	</script>
	</f:verbatim>

	</sakai:view_container>
</f:view> 
