<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="Messages" var="msgs"/>

<f:view>

	<sakai:view_container title="Lamstwo Tool">
		<style type="text/css">
			@import url("/sakai-lamstwo-tool/css/Lamstwo.css");
		</style>

		<script type="text/javascript" src="/library/js/headscripts.js"></script>
		<script type="text/javascript" src="lib/tigra/tree.js"></script>
		<script type="text/javascript" src="lib/tigra/tree_tpl.js"></script>
		
		<sakai:script contextBase="/sakai-jsf-resource" path="/inputDate/calendar1.js"/>
		<sakai:script contextBase="/sakai-jsf-resource" path="/inputDate/calendar2.js"/>

		<f:verbatim>
		    <script type="text/javascript">
			    //<![CDATA[
			    var url = '</f:verbatim><h:outputText escape="false" value="#{LamstwoBean.authorURL}" /><f:verbatim>';
			    var lessonCreated = </f:verbatim><h:outputText escape="false" value="#{LamstwoBean.lessonCreated}" /><f:verbatim>;
   				var options = "location=0,toolbar=0,menubar=0,statusbar=0,width=796,height=570,resizable";
				//]]>
			</script>
		</f:verbatim>
		
		<script type="text/javascript">
		    //<![CDATA[
		    
		    function nextStage() {
	  			var stage1 = document.getElementById("stage1");
  				var stage2 = document.getElementById("stage2");
  				
  				stage1.style.display = 'none';
  				stage2.style.display = 'block';
	  		}
	  		
	  		function previousStage() {
	  			var stage1 = document.getElementById("stage1");
  				var stage2 = document.getElementById("stage2");
  				
  				stage2.style.display = 'none';
  				stage1.style.display = 'block';
  				
  				// when a user hits previous after a validation error, the next button will be disabled.
		    	document.getElementById("addUpdateItem:tree:nextButton").disabled = false;
	  		}
		    
		    function selectSequence(id) {
		    	var itemSequenceId = document.getElementById('addUpdateItem:itemSequenceId');
		    	itemSequenceId.value = id;
		    	
		    	document.getElementById("addUpdateItem:tree:nextButton").disabled = false;
		    }

			function openAuthor() {
				//url = url + "&notifyCloseURL=" + escape(window.location.href);
				openWindow(url, "author", options);
			}
			//]]>
		</script>

		<h:form id="listItems">
			<sakai:tool_bar>
				<sakai:tool_bar_item action="#{LamstwoBean.processActionList}" value="#{msgs.lamstwo_list}" />
			</sakai:tool_bar>
		</h:form>

		<sakai:view_content>
			<h:form id="addUpdateItem">
			 	<sakai:view_title value="#{msgs.lamstwo_add}"/>

				<sakai:messages />

				<sakai:instruction_message value="Hello, #{LamstwoBean.currentUserDisplayName}"/>
 				
 				<%-- Only render tigra tree when we are creating a new lesson --%>
 				<f:subview id="tree" rendered="#{not LamstwoBean.lessonCreated}">
 					<div id="stage1" style="display: none;">
						<f:verbatim>
							<script type="text/javascript">
							    //<![CDATA[
								var TREE_ITEMS =
							</f:verbatim><h:outputText value="#{LamstwoBean.learningDesigns}"></h:outputText><f:verbatim>
								var tree = new tree(TREE_ITEMS, TREE_TPL);
								//]]>
							</script>
						</f:verbatim>
						
						<sakai:button_bar>
							<h:commandButton value="#{msgs.lamstwo_open_author}" onclick="openAuthor(); return false;" />
							<h:commandButton id="nextButton" value="#{msgs.lamstwo_next}" onclick="nextStage(); return false;" disabled="true"/>
		                </sakai:button_bar>
					</div>
				</f:subview>
				
				<h:inputHidden id="itemSequenceId" value="#{LamstwoBean.itemSequenceId}" rendered="#{not LamstwoBean.lessonCreated}">
					<f:validateLongRange minimum="1"/>
				</h:inputHidden>
				
				<div id="stage2" style="display: none;">
					<sakai:panel_edit>
					 	<h:outputLabel for="itemText" value="#{msgs.lamstwo_text}"/>
				 		<h:inputText id="itemText" value="#{LamstwoBean.itemText}" size="70" required="true">
				 			<f:validateLength minimum="2" maximum="255" />
						</h:inputText>
				 	
				 		<h:outputLabel for="itemIntroduction" value="#{msgs.lamstwo_introduction}"/>
				 		<h:inputTextarea id="itemIntroduction" value="#{LamstwoBean.itemIntroduction}" rows="3" cols="70">
				 			<f:validateLength maximum="255"/>
				 		</h:inputTextarea>
						
					 	<h:outputLabel for="itemHidden" value="#{msgs.lamstwo_hidden}" />
					 	<h:selectBooleanCheckbox id="itemHidden" title="#{msgs.lamstwo_hidden}" 
					 		value="#{LamstwoBean.itemHidden}">
						</h:selectBooleanCheckbox>
	
						<%-- Only render itemSchedule and itemStartDate when creating a new lesson --%>
					 	<h:outputLabel for="itemSchedule" value="#{msgs.lamstwo_schedule}" rendered="#{not LamstwoBean.lessonCreated}" />
					 	<h:selectBooleanCheckbox id="itemSchedule" title="#{msgs.lamstwo_schedule}" rendered="#{not LamstwoBean.lessonCreated}"
					 		value="#{LamstwoBean.itemSchedule}">
						</h:selectBooleanCheckbox>
						
						<h:outputLabel for="itemStartDate" value="#{msgs.lamstwo_startdate}" rendered="#{not LamstwoBean.lessonCreated}"/>
						<sakai:input_date id="itemStartDate" value="#{LamstwoBean.itemStartDate}" showDate="true" showTime="true" rendered="#{not LamstwoBean.lessonCreated}">
					 	</sakai:input_date>
				 	</sakai:panel_edit>
				 	
					<sakai:button_bar>
						<h:commandButton value="#{msgs.lamstwo_previous}" onclick="previousStage(); return false;" rendered="#{not LamstwoBean.lessonCreated}" />
						<h:commandButton value="#{msgs.lamstwo_add}" action="#{LamstwoBean.processActionAdd}" />
	                </sakai:button_bar>
                </div>

			 </h:form>
  		</sakai:view_content>	
  		
  		<script type="text/javascript">
			//<![CDATA[
			var sequenceIdElem = document.getElementById("addUpdateItem:itemSequenceId");
			
			var sequenceId = null;			
			if (sequenceIdElem != null) {
				sequenceId = sequenceIdElem.value;
			}
			
  			if (!lessonCreated && (sequenceId == "0")) {
  				document.getElementById("stage1").style.display = 'block';
  			} else {
  				document.getElementById("stage2").style.display = 'block';
  			}  			
	  		//]]>	
  		</script>
	</sakai:view_container>
</f:view> 
