<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="Messages" var="msgs"/>

<f:view>
	<sakai:view_container title="Lamstwo Tool" >

	<f:verbatim>
	<script type="text/javascript"> 
		function loadMonitor() {
			window.location = "</f:verbatim><h:outputText value="#{LamstwoBean.monitorURL}" escape="false" /><f:verbatim>";
		}
		
		setTimeout(loadMonitor(), 5000);
	</script>
	</f:verbatim>

	</sakai:view_container>
</f:view> 