
 
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lawiki10_user;
DROP TABLE IF EXISTS tl_lawiki10_attachment;
DROP TABLE IF EXISTS tl_lawiki10_session;
DROP TABLE IF EXISTS tl_lawiki10_wiki;
SET FOREIGN_KEY_CHECKS=1;





