SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lantbk11_conditions;
DROP TABLE IF EXISTS tl_lantbk11_user;
DROP TABLE IF EXISTS tl_lantbk11_session;
DROP TABLE IF EXISTS tl_lantbk11_notebook;
SET FOREIGN_KEY_CHECKS=1;