-- CVS ID: $Id$
 
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_mdquiz10_user;
DROP TABLE IF EXISTS tl_mdquiz10_attachment;
DROP TABLE IF EXISTS tl_mdquiz10_session;
DROP TABLE IF EXISTS tl_mdquiz10_mdlquiz;
SET FOREIGN_KEY_CHECKS=1;





