alter table tl_lanb11_attachment drop foreign key FK2A616F52D4E85AA3;
alter table tl_lanb11_session drop foreign key FK2C0EB2C7D4E85AA3;
alter table tl_lanb11_user drop foreign key FK25BD113A285CA05D;
drop table if exists tl_lanb11_attachment;
drop table if exists tl_lanb11_content;
drop table if exists tl_lanb11_session;
drop table if exists tl_lanb11_user;
create table tl_lanb11_attachment (attachment_id bigint not null auto_increment, filename varchar(255) not null, online_file bit not null, nb_content_uid bigint, uuid bigint not null, version_id bigint, primary key (attachment_id));
create table tl_lanb11_content (uid bigint not null auto_increment, content longtext, creator_user_id bigint, date_created datetime, date_updated datetime, define_later bit, force_offline bit, reflect_on_activity bit, reflect_instructions longtext, content_in_use bit, nb_content_id bigint not null, offline_instructions longtext, online_instructions longtext, title longtext, primary key (uid));
create table tl_lanb11_session (uid bigint not null auto_increment, nb_content_uid bigint, nb_session_id bigint not null, nb_session_name varchar(255) not null, session_end_date datetime, session_start_date datetime, session_status varchar(100), primary key (uid));
create table tl_lanb11_user (uid bigint not null auto_increment, fullname varchar(255), nb_session_uid bigint, user_id bigint not null, username varchar(255), user_status varchar(50), primary key (uid));
alter table tl_lanb11_attachment add index FK2A616F52D4E85AA3 (nb_content_uid), add constraint FK2A616F52D4E85AA3 foreign key (nb_content_uid) references tl_lanb11_content (uid);
alter table tl_lanb11_session add index FK2C0EB2C7D4E85AA3 (nb_content_uid), add constraint FK2C0EB2C7D4E85AA3 foreign key (nb_content_uid) references tl_lanb11_content (uid);
alter table tl_lanb11_user add index FK25BD113A285CA05D (nb_session_uid), add constraint FK25BD113A285CA05D foreign key (nb_session_uid) references tl_lanb11_session (uid);
