INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time
)
VALUES
(
'lanb11',
'nbService',
'NoticeboardX',
'Displays a NoticeboardX',
'nb',
'@tool_version@',
0,
2,
'tool/lanb11/learning/learner.do',
'tool/lanb11/learning/author.do',
'tool/lanb11/learning/teacher.do',
'tool/lanb11/authoring/authoring.do',
'tool/lanb11/monitoring/monitoring.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lanb11',
'org.lamsfoundation.lams.tool.noticeboard.ApplicationResources',
NOW(),
NOW()
);