SET FOREIGN_KEY_CHECKS=0;
drop table if exists tl_eueadv10_attachment;
drop table if exists tl_eueadv10_item_instruction;
drop table if exists tl_eueadv10_eadventure;
drop table if exists tl_eueadv10_eadventure_item;
drop table if exists tl_eueadv10_item_log;
drop table if exists tl_eueadv10_session;
drop table if exists tl_eueadv10_user;
drop table if exists tl_eueadv10_condition;
drop table if exists tl_eueadv10_condition_expression;
SET FOREIGN_KEY_CHECKS=1;