INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
admin_url,
language_file,
create_date_time,
modified_date_time
)
VALUES
(
'lazoom10',
'zoomService',
'Zoom',
'Web conferencing using Zoom',
'zoom',
'@tool_version@',
0,
2,
'tool/lazoom10/learning/start.do?mode=learner',
'tool/lazoom10/learning/start.do?mode=author',
'tool/lazoom10/learning/start.do?mode=teacher',
'tool/lazoom10/authoring/start.do',
'tool/lazoom10/monitoring/start.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lazoom10',
'tool/lazoom10/admin/start.do',
'org.lamsfoundation.lams.tool.zoom.ApplicationResources',
NOW(),
NOW()
)
