-- $Id$

insert into tl_lawiki10_wiki (ID,TITLE, ALLOWANNOMITY, FORCEOFFLINE, LOCKWHENFINISHED, INSTRUCTIONS,
ONLINEINSTRUCTIONS, OFFLINEINSTRUCTIONS) VALUES (1, "TEST WIKI", false, false, false, "TEST INSTRUCTIONS", "TEST ONLINE INSTRUCTIONS", "TEST OFFLINE INSTRUCTIONS");

insert into tl_lawiki10_message (ID, SUBJECT, BODY, ISAUTHORED, ISANNONYMOUS, WIKI, PARENT) VALUES  (2, "TITLE", "BODY", true, false, 1, NULL) ;
