DROP INDEX PRIMARY ON DEFAULT_SCHEMA.genericentity;
DROP INDEX PRIMARY ON DEFAULT_SCHEMA.forum;
DROP INDEX FK3FF9501D1B ON DEFAULT_SCHEMA.forum;
DROP INDEX PRIMARY ON DEFAULT_SCHEMA.message;
DROP INDEX FK63B68BE78C3DFCAA ON DEFAULT_SCHEMA.message;
DROP INDEX FK63B68BE73FF9501 ON DEFAULT_SCHEMA.message;
DROP INDEX FK63B68BE7D1B ON DEFAULT_SCHEMA.message;
DROP INDEX PRIMARY ON DEFAULT_SCHEMA.attachment;
DROP INDEX FKA7E145233FF9501 ON DEFAULT_SCHEMA.attachment;
DROP INDEX FKA7E14523D1B ON DEFAULT_SCHEMA.attachment;

DROP TABLE DEFAULT_SCHEMA.attachment;
DROP TABLE DEFAULT_SCHEMA.message;
DROP TABLE DEFAULT_SCHEMA.forum;
DROP TABLE DEFAULT_SCHEMA.genericentity;





