SET FOREIGN_KEY_CHECKS=0;
drop table if exists tl_lafrum11_attachment;
drop table if exists tl_lafrum11_forum;
drop table if exists tl_lafrum11_forum_user;
drop table if exists tl_lafrum11_message;
drop table if exists tl_lafrum11_message_seq;
drop table if exists tl_lafrum11_message_rating;
drop table if exists tl_lafrum11_tool_session;
drop table if exists tl_lafrum11_report;
drop table if exists tl_lafrum11_condition_topics;
drop table if exists tl_lafrum11_conditions;
drop table if exists tl_lafrum11_timestamp;
SET FOREIGN_KEY_CHECKS=1;