
INSERT INTO GENERICENTITY (ID, CREATED
								) VALUES (1,
		NOW());
INSERT INTO GENERICENTITY (ID, CREATED
								) VALUES (2,
		NOW());
insert into FORUM (ID,TITLE, ALLOWANNOMITY, FORCEOFFLINE, LOCKWHENFINISHED, INSTRUCTIONS, 
ONLINEINSTRUCTIONS, OFFLINEINSTRUCTIONS) VALUES (1, "TEST FORUM", false, false, false, "TEST INSTRUCTIONS", "TEST ONLINE INSTRUCTIONS", "TEST OFFLINE INSTRUCTIONS");
insert into MESSAGE (ID, SUBJECT, BODY, ISAUTHORED, ISANNONYMOUS, FORUM, PARENT) VALUES  (2, "TITLE", "BODY", true, false, 1, NULL) ;