-- CVS ID: $Id$
 
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_dlfrum10_user;
DROP TABLE IF EXISTS tl_dlfrum10_attachment;
DROP TABLE IF EXISTS tl_dlfrum10_session;
DROP TABLE IF EXISTS tl_dlfrum10_dotLRNForum;
SET FOREIGN_KEY_CHECKS=1;





