alter table tl_lawook10_attachment drop foreign key FK89B47F371913B1B;
alter table tl_lawook10_session drop foreign key FKCFBF85C671913B1B;
alter table tl_lawook10_user drop foreign key FKC7EA369B84954B4;
drop table if exists tl_lawook10_attachment;
drop table if exists tl_lawook10_configuration;
drop table if exists tl_lawook10_session;
drop table if exists tl_lawook10_user;
drop table if exists tl_lawook10_wookie;
create table tl_lawook10_attachment (uid bigint not null auto_increment, file_version_id bigint, file_type varchar(255), file_name varchar(255), file_uuid bigint, create_date datetime, wookie_uid bigint, primary key (uid));
create table tl_lawook10_configuration (uid bigint not null auto_increment, config_key varchar(30) unique, config_value longtext, primary key (uid));
create table tl_lawook10_session (uid bigint not null auto_increment, session_end_date datetime, session_start_date datetime, status integer, session_id bigint, session_name varchar(250), wookie_uid bigint, widget_shared_data_key varchar(63), widget_height integer, widget_width integer, widget_maximise bit, widget_identifier longtext, primary key (uid));
create table tl_lawook10_user (uid bigint not null auto_increment, user_id bigint, last_name varchar(255), login_name varchar(255), first_name varchar(255), finishedActivity bit, wookie_session_uid bigint, entry_uid bigint, user_widget_url longtext, primary key (uid));
create table tl_lawook10_wookie (uid bigint not null auto_increment, create_date datetime, update_date datetime, create_by integer, title varchar(255), instructions longtext, run_offline bit, lock_on_finished bit, reflect_on_activity bit, online_instructions longtext, offline_instructions longtext, content_in_use bit, define_later bit, tool_content_id bigint, reflect_instructions longtext, widget_author_url longtext, widget_height integer, widget_width integer, widget_maximise bit, widget_identifier longtext, primary key (uid));
alter table tl_lawook10_attachment add index FK89B47F371913B1B (wookie_uid), add constraint FK89B47F371913B1B foreign key (wookie_uid) references tl_lawook10_wookie (uid);
alter table tl_lawook10_session add index FKCFBF85C671913B1B (wookie_uid), add constraint FKCFBF85C671913B1B foreign key (wookie_uid) references tl_lawook10_wookie (uid);
alter table tl_lawook10_user add index FKC7EA369B84954B4 (wookie_session_uid), add constraint FKC7EA369B84954B4 foreign key (wookie_session_uid) references tl_lawook10_session (uid);
