SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lapixl10_user;
DROP TABLE IF EXISTS tl_lapixl10_session;
DROP TABLE IF EXISTS tl_lapixl10_pixlr;
DROP TABLE IF EXISTS tl_lapixl10_configuration;
SET FOREIGN_KEY_CHECKS=1;