alter table lams_text_search_condition drop foreign key FK69B884B21E70F543;
alter table tl_lapixl10_attachment drop foreign key FK951F889ACB8ADA74;
alter table tl_lapixl10_session drop foreign key FKE5C05E7FCB8ADA74;
alter table tl_lapixl10_user drop foreign key FK9A39C08236E23005;
drop table if exists lams_branch_condition;
drop table if exists lams_text_search_condition;
drop table if exists tl_lapixl10_attachment;
drop table if exists tl_lapixl10_configuration;
drop table if exists tl_lapixl10_pixlr;
drop table if exists tl_lapixl10_session;
drop table if exists tl_lapixl10_user;
create table lams_branch_condition (condition_id bigint not null auto_increment, condition_ui_id integer, order_id integer, name varchar(255), display_name varchar(255), type varchar(255), start_value varchar(255), end_value varchar(255), exact_match_value varchar(255), primary key (condition_id));
create table lams_text_search_condition (condition_id bigint not null, text_search_all_words varchar(255), text_search_phrase varchar(255), text_search_any_words varchar(255), text_search_excluded_words varchar(255), primary key (condition_id));
create table tl_lapixl10_attachment (uid bigint not null auto_increment, file_version_id bigint, file_type varchar(255), file_name varchar(255), file_uuid bigint, create_date datetime, pixlr_uid bigint, primary key (uid));
create table tl_lapixl10_configuration (uid bigint not null auto_increment, config_key varchar(30) unique, config_value longtext, primary key (uid));
create table tl_lapixl10_pixlr (uid bigint not null auto_increment, create_date datetime, update_date datetime, create_by bigint, title varchar(255), instructions longtext, run_offline bit, lock_on_finished bit, reflect_on_activity bit, allow_view_others_images bit, online_instructions longtext, offline_instructions longtext, content_in_use bit, define_later bit, tool_content_id bigint, image_file_name longtext, image_width bigint, image_height bigint, reflect_instructions longtext, primary key (uid));
create table tl_lapixl10_session (uid bigint not null auto_increment, session_end_date datetime, session_start_date datetime, status integer, session_id bigint, session_name varchar(250), pixlr_uid bigint, primary key (uid));
create table tl_lapixl10_user (uid bigint not null auto_increment, user_id bigint, last_name varchar(255), login_name varchar(255), first_name varchar(255), finishedActivity bit, pixlr_session_uid bigint, entry_uid bigint, image_file_name longtext, imageHeight bigint, imageWidth bigint, imageHidden bit, primary key (uid));
alter table lams_text_search_condition add index FK69B884B21E70F543 (condition_id), add constraint FK69B884B21E70F543 foreign key (condition_id) references lams_branch_condition (condition_id);
alter table tl_lapixl10_attachment add index FK951F889ACB8ADA74 (pixlr_uid), add constraint FK951F889ACB8ADA74 foreign key (pixlr_uid) references tl_lapixl10_pixlr (uid);
alter table tl_lapixl10_session add index FKE5C05E7FCB8ADA74 (pixlr_uid), add constraint FKE5C05E7FCB8ADA74 foreign key (pixlr_uid) references tl_lapixl10_pixlr (uid);
alter table tl_lapixl10_user add index FK9A39C08236E23005 (pixlr_session_uid), add constraint FK9A39C08236E23005 foreign key (pixlr_session_uid) references tl_lapixl10_session (uid);
