alter table lams_text_search_condition drop foreign key FK69B884B21E70F543;
alter table tl_lavidr10_attachment drop foreign key FKBF292946C1D77330;
alter table tl_lavidr10_comment drop foreign key FKD6C3C91C5C3E37F1;
alter table tl_lavidr10_comment drop foreign key FKD6C3C91C1EA54C27;
alter table tl_lavidr10_comment drop foreign key FKD6C3C91CB1418D4B;
alter table tl_lavidr10_conditions drop foreign key FKFCB606DBCA197570;
alter table tl_lavidr10_conditions drop foreign key FKFCB606DB3E8DC190;
alter table tl_lavidr10_rating drop foreign key FK9BA30B405C3E37F1;
alter table tl_lavidr10_rating drop foreign key FK9BA30B401EA54C27;
alter table tl_lavidr10_rating drop foreign key FK9BA30B40B1418D4B;
alter table tl_lavidr10_recording drop foreign key FKC94A9D6E5C3E37F1;
alter table tl_lavidr10_recording drop foreign key FKC94A9D6EB1418D4B;
alter table tl_lavidr10_session drop foreign key FK146E5D53C1D77330;
alter table tl_lavidr10_user drop foreign key FKF184522E5C3E37F1;
drop table if exists lams_branch_condition;
drop table if exists lams_text_search_condition;
drop table if exists tl_lavidr10_attachment;
drop table if exists tl_lavidr10_comment;
drop table if exists tl_lavidr10_conditions;
drop table if exists tl_lavidr10_rating;
drop table if exists tl_lavidr10_recording;
drop table if exists tl_lavidr10_session;
drop table if exists tl_lavidr10_user;
drop table if exists tl_lavidr10_videorecorder;
create table lams_branch_condition (condition_id bigint not null auto_increment, condition_ui_id integer, order_id integer, name varchar(255), display_name varchar(255), type varchar(255), start_value varchar(255), end_value varchar(255), exact_match_value varchar(255), primary key (condition_id));
create table lams_text_search_condition (condition_id bigint not null, text_search_all_words varchar(255), text_search_phrase varchar(255), text_search_any_words varchar(255), text_search_excluded_words varchar(255), primary key (condition_id));
create table tl_lavidr10_attachment (uid bigint not null auto_increment, file_version_id bigint, file_type varchar(255), file_name varchar(255), file_uuid bigint, create_date datetime, videoRecorder_uid bigint, primary key (uid));
create table tl_lavidr10_comment (uid bigint not null auto_increment, create_date datetime, create_by bigint, videoRecorder_recording_uid bigint, comment longtext, videoRecorder_session_uid bigint, primary key (uid));
create table tl_lavidr10_conditions (condition_id bigint not null, content_uid bigint, primary key (condition_id));
create table tl_lavidr10_rating (uid bigint not null auto_increment, create_date datetime, create_by bigint, videoRecorder_recording_uid bigint, rating float, videoRecorder_session_uid bigint, primary key (uid));
create table tl_lavidr10_recording (uid bigint not null auto_increment, tool_content_id bigint, create_date datetime, update_date datetime, create_by bigint, title varchar(255), description longtext, rating float, is_just_sound bit, is_local bit, videoRecorder_session_uid bigint, filename varchar(255), primary key (uid));
create table tl_lavidr10_session (uid bigint not null auto_increment, session_end_date datetime, session_start_date datetime, status integer, session_id bigint, session_name varchar(250), content_folder_id varchar(32), videoRecorder_uid bigint, primary key (uid));
create table tl_lavidr10_user (uid bigint not null auto_increment, user_id bigint, last_name varchar(255), login_name varchar(255), first_name varchar(255), finishedActivity bit, videoRecorder_session_uid bigint, entry_uid bigint, primary key (uid));
create table tl_lavidr10_videorecorder (uid bigint not null auto_increment, create_date datetime, update_date datetime, create_by bigint, title varchar(255), instructions longtext, reflect_on_activity bit, reflect_instructions longtext, run_offline bit, lock_on_finished bit, allow_use_voice bit, allow_use_camera bit, allow_learner_video_visibility bit, allow_comments bit, allow_ratings bit, export_offline bit, export_all bit, online_instructions longtext, offline_instructions longtext, content_in_use bit, define_later bit, tool_content_id bigint, primary key (uid));
alter table lams_text_search_condition add index FK69B884B21E70F543 (condition_id), add constraint FK69B884B21E70F543 foreign key (condition_id) references lams_branch_condition (condition_id);
alter table tl_lavidr10_attachment add index FKBF292946C1D77330 (videoRecorder_uid), add constraint FKBF292946C1D77330 foreign key (videoRecorder_uid) references tl_lavidr10_videorecorder (uid);
alter table tl_lavidr10_comment add index FKD6C3C91C5C3E37F1 (videoRecorder_session_uid), add constraint FKD6C3C91C5C3E37F1 foreign key (videoRecorder_session_uid) references tl_lavidr10_session (uid);
alter table tl_lavidr10_comment add index FKD6C3C91C1EA54C27 (videoRecorder_recording_uid), add constraint FKD6C3C91C1EA54C27 foreign key (videoRecorder_recording_uid) references tl_lavidr10_recording (uid);
alter table tl_lavidr10_comment add index FKD6C3C91CB1418D4B (create_by), add constraint FKD6C3C91CB1418D4B foreign key (create_by) references tl_lavidr10_user (uid);
alter table tl_lavidr10_conditions add index FKFCB606DBCA197570 (content_uid), add constraint FKFCB606DBCA197570 foreign key (content_uid) references tl_lavidr10_videorecorder (uid);
alter table tl_lavidr10_conditions add index FKFCB606DB3E8DC190 (condition_id), add constraint FKFCB606DB3E8DC190 foreign key (condition_id) references lams_text_search_condition (condition_id);
alter table tl_lavidr10_rating add index FK9BA30B405C3E37F1 (videoRecorder_session_uid), add constraint FK9BA30B405C3E37F1 foreign key (videoRecorder_session_uid) references tl_lavidr10_session (uid);
alter table tl_lavidr10_rating add index FK9BA30B401EA54C27 (videoRecorder_recording_uid), add constraint FK9BA30B401EA54C27 foreign key (videoRecorder_recording_uid) references tl_lavidr10_recording (uid);
alter table tl_lavidr10_rating add index FK9BA30B40B1418D4B (create_by), add constraint FK9BA30B40B1418D4B foreign key (create_by) references tl_lavidr10_user (uid);
alter table tl_lavidr10_recording add index FKC94A9D6E5C3E37F1 (videoRecorder_session_uid), add constraint FKC94A9D6E5C3E37F1 foreign key (videoRecorder_session_uid) references tl_lavidr10_session (uid);
alter table tl_lavidr10_recording add index FKC94A9D6EB1418D4B (create_by), add constraint FKC94A9D6EB1418D4B foreign key (create_by) references tl_lavidr10_user (uid);
alter table tl_lavidr10_session add index FK146E5D53C1D77330 (videoRecorder_uid), add constraint FK146E5D53C1D77330 foreign key (videoRecorder_uid) references tl_lavidr10_videorecorder (uid);
alter table tl_lavidr10_user add index FKF184522E5C3E37F1 (videoRecorder_session_uid), add constraint FKF184522E5C3E37F1 foreign key (videoRecorder_session_uid) references tl_lavidr10_session (uid);
