INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lavidr10',
'videoRecorderService',
'VideoRecorder',
'VideoRecorder',
'videoRecorder',
'@tool_version@',
0,
2,
'tool/lavidr10/learning.do?mode=learner',
'tool/lavidr10/learning.do?mode=author',
'tool/lavidr10/learning.do?mode=teacher',
'tool/lavidr10/authoring.do',
'tool/lavidr10/monitoring.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lavidr10',
'org.lamsfoundation.lams.tool.videoRecorder.ApplicationResources',
NOW(),
NOW(),
1
)