-- CVS ID: $Id$
 
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_mdwiki10_user;
DROP TABLE IF EXISTS tl_mdwiki10_attachment;
DROP TABLE IF EXISTS tl_mdwiki10_session;
DROP TABLE IF EXISTS tl_mdwiki10_mdlwiki;
SET FOREIGN_KEY_CHECKS=1;





