SET AUTOCOMMIT = 0;
set FOREIGN_KEY_CHECKS = 0;

--  LDEV-4746 Allow more options in a QB question

ALTER TABLE lams_qb_tool_question MODIFY COLUMN display_order TINYINT UNSIGNED NOT NULL DEFAULT 1;

COMMIT;
SET AUTOCOMMIT = 1;
set FOREIGN_KEY_CHECKS = 1;

