SET FOREIGN_KEY_CHECKS=0;
drop table if exists tl_ladaco10_attachment;
drop table if exists tl_ladaco10_contents;
drop table if exists tl_ladaco10_questions;
drop table if exists tl_ladaco10_answer_options;
drop table if exists tl_ladaco10_question_log;
drop table if exists tl_ladaco10_session;
drop table if exists tl_ladaco10_user;
drop table if exists tl_ladaco10_answers;
SET FOREIGN_KEY_CHECKS=1;