/****************************************************************
 * Copyright (C) 2005 LAMS Foundation (http://lamsfoundation.org)
 * =============================================================
 * License Information: http://lamsfoundation.org/licensing/lams/2.0/
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301
 * USA
 * 
 * http://www.gnu.org/licenses/gpl.txt
 * ****************************************************************
 */

/**
 * @author Ozgur Demirtas
 * 
 * Created on 8/03/2005
 * 
 * initializes the tool's authoring mode  
 */

/**
 * Tool path The URL path for the tool should be <lamsroot>/tool/$TOOL_SIG.
 * 
 * CONTENT_LOCKED ->CONTENT_IN_USE 
 * 
 * QaStarterAction loads the default content and initializes the presentation Map
 * Requests can come either from authoring envuironment or from the monitoring environment for Edit Activity screen
 * 
 * Check QaUtils.createAuthoringUser again User Management Service is ready
 * 
 * */

/**
 *
 * Tool Content:
 *
 * While tool's manage their own content, the LAMS core and the tools work together to create and use the content. 
 * The tool content id (toolContentID) is the key by which the tool and the LAMS core discuss data - 
 * it is generated by the LAMS core and supplied to the tool whenever content needs to be stored. 
 * The LAMS core will refer to the tool content id whenever the content needs to be used. 
 * Tool content will be covered in more detail in following sections.
 *
 * Each tool will have one piece of content that is the default content. 
 * The tool content id for this content is created as part of the installation process. 
 * Whenever a tool is asked for some tool content that does not exist, it should supply the default tool content. 
 * This will allow the system to render the normal screen, albeit with useless information, rather than crashing. 
 */

/**
 *
 * Authoring URL: 
 *
 * The tool must supply an authoring module, which will be called to create new content or edit existing content. It will be called by an authoring URL using the following format: ?????
 * The initial data displayed on the authoring screen for a new tool content id may be the default tool content.
 *
 * Authoring UI data consists of general Activity data fields and the Tool specific data fields.
 * The authoring interface will have three tabs. The mandatory (and suggested) fields are given. Each tool will have its own fields which it will add on any of the three tabs, as appropriate to the tabs' function.
 *
 * Basic: Displays the basic set of fields that are needed for the tool, and it could be expected that a new LAMS user would use. Mandatory fields: Title, Instructions.
 * Advanced: Displays the extra fields that would be used by experienced LAMS users. Optional fields: Lock On Finish, Make Responses Anonymous
 * Instructions: Displays the "instructions" fields for teachers. Mandatory fields: Online instructions, Offline instructions, Document upload.
 * The "Define Later" and "Run Offline" options are set on the Flash authoring part, and not on the tool's authoring screens.
 *
 * Preview The tool must be able to show the specified content as if it was running in a lesson. It will be the learner url with tool access mode set to ToolAccessMode.AUTHOR.
 * Export The tool must be able to export its tool content for part of the overall learning design export.
 *
 * The format of the serialization for export is XML. Tool will define extra namespace inside the <Content> element to add a new data element (type). Inside the data element, it can further define more structures and types as it seems fit.
 * The data elements must be "version" aware. The data elements must be "type" aware if they are to be shared between Tools.
 * 
 * 
 <!-- ========== Action Mapping Definitions =================================== -->
 <action-mappings>
 <!--Authoring Starter  -->
 <action
 path="/authoringStarter"
 type="org.lamsfoundation.lams.tool.qa.web.QaStarterAction"
 name="QaAuthoringForm"
 scope="request"
 unknown="false"
 validate="false"
 >

 <forward
 name="load"
 path="/AuthoringMaincontent.jsp"
 redirect="false"
 />

 <forward
 name="loadViewOnly"
 path="/authoring/AuthoringTabsHolder.jsp"
 redirect="false"
 />

 <forward
 name="loadMonitoring"
 path="/monitoring/MonitoringMaincontent.jsp"
 redirect="false"
 />

 <forward
 name="refreshMonitoring"
 path="/monitoring/MonitoringMaincontent.jsp"
 redirect="false"
 />

 </action>  

 * 
 */

/* $$Id$$ */
package org.lamsfoundation.lams.tool.qa.web;

import java.io.IOException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.Globals;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.lamsfoundation.lams.learningdesign.TextSearchConditionComparator;
import org.lamsfoundation.lams.tool.qa.QaAppConstants;
import org.lamsfoundation.lams.tool.qa.QaCondition;
import org.lamsfoundation.lams.tool.qa.QaContent;
import org.lamsfoundation.lams.tool.qa.QaQueContent;
import org.lamsfoundation.lams.tool.qa.dto.QaGeneralAuthoringDTO;
import org.lamsfoundation.lams.tool.qa.dto.QaQuestionDTO;
import org.lamsfoundation.lams.tool.qa.service.IQaService;
import org.lamsfoundation.lams.tool.qa.service.QaServiceProxy;
import org.lamsfoundation.lams.tool.qa.util.QaApplicationException;
import org.lamsfoundation.lams.tool.qa.util.QaUtils;
import org.lamsfoundation.lams.tool.qa.web.form.QaAuthoringForm;
import org.lamsfoundation.lams.util.WebUtil;
import org.lamsfoundation.lams.web.util.AttributeNames;
import org.lamsfoundation.lams.web.util.SessionMap;

/**
 * 
 * @author Ozgur Demirtas
 */
public class QaStarterAction extends Action implements QaAppConstants {
    static Logger logger = Logger.getLogger(QaStarterAction.class.getName());

    @Override
    public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
	    HttpServletResponse response) throws IOException, ServletException, QaApplicationException {

	QaUtils.cleanUpSessionAbsolute(request);
	QaAuthoringForm qaAuthoringForm = (QaAuthoringForm) form;

	String contentFolderID = WebUtil.readStrParam(request, AttributeNames.PARAM_CONTENT_FOLDER_ID);
	qaAuthoringForm.setContentFolderID(contentFolderID);

	QaGeneralAuthoringDTO qaGeneralAuthoringDTO = new QaGeneralAuthoringDTO();
	qaGeneralAuthoringDTO.setContentFolderID(contentFolderID);

	qaAuthoringForm.resetRadioBoxes();

	IQaService qaService = null;
	if (getServlet() == null || getServlet().getServletContext() == null) {
	    qaService = qaAuthoringForm.getQaService();
	} else {
	    qaService = QaServiceProxy.getQaService(getServlet().getServletContext());
	}

	qaGeneralAuthoringDTO.setCurrentTab("1");

	qaGeneralAuthoringDTO.setMonitoringOriginatedDefineLater(new Boolean(false).toString());
	String servletPath = request.getServletPath();
	String requestedModule = null;
	if (servletPath.indexOf("authoringStarter") > 0) {
	    qaGeneralAuthoringDTO.setActiveModule(QaAppConstants.AUTHORING);
	    qaGeneralAuthoringDTO.setDefineLaterInEditMode(new Boolean(true).toString());
	    qaGeneralAuthoringDTO.setShowAuthoringTabs(new Boolean(true).toString());
	    qaAuthoringForm.setActiveModule(QaAppConstants.AUTHORING);
	    requestedModule = QaAppConstants.AUTHORING;
	} else {
	    //request is for define later module either direcly from define later url or monitoring url
	    qaGeneralAuthoringDTO.setActiveModule(QaAppConstants.DEFINE_LATER);
	    qaGeneralAuthoringDTO.setDefineLaterInEditMode(new Boolean(true).toString());
	    qaGeneralAuthoringDTO.setShowAuthoringTabs(new Boolean(false).toString());
	    qaAuthoringForm.setActiveModule(QaAppConstants.DEFINE_LATER);
	    requestedModule = QaAppConstants.DEFINE_LATER;

	    if (servletPath.indexOf("monitoring") > 0) {
		//request is from monitoring  url
		qaGeneralAuthoringDTO.setMonitoringOriginatedDefineLater(new Boolean(true).toString());
	    }
	}
	qaGeneralAuthoringDTO.setRequestedModule(requestedModule);

	/* in development this needs to be called only once. */
	/* QaUtils.configureContentRepository(request); */

	String sourceMcStarter = (String) request.getAttribute(QaAppConstants.SOURCE_MC_STARTER);

	boolean validateSignature = readSignature(request, mapping, qaService, qaGeneralAuthoringDTO, qaAuthoringForm);

	/* mark the http session as an authoring activity */
	qaGeneralAuthoringDTO.setTargetMode(QaAppConstants.TARGET_MODE_AUTHORING);

	/*
	 * find out whether the request is coming from monitoring module for EditActivity tab or from authoring
	 * environment url
	 */
	//no problems getting the default content, will render authoring screen
	String strToolContentID = "";
	/* the authoring url must be passed a tool content id */
	strToolContentID = request.getParameter(AttributeNames.PARAM_TOOL_CONTENT_ID);
	qaGeneralAuthoringDTO.setToolContentID(strToolContentID);

	SessionMap sessionMap = new SessionMap();
	List sequentialCheckedCa = new LinkedList();
	sessionMap.put(QaAppConstants.ACTIVITY_TITLE_KEY, "");
	sessionMap.put(QaAppConstants.ACTIVITY_INSTRUCTIONS_KEY, "");
	qaAuthoringForm.setHttpSessionID(sessionMap.getSessionID());
	qaGeneralAuthoringDTO.setHttpSessionID(sessionMap.getSessionID());

	String defaultContentId = null;
	// pay attention here: remove
	// request.getSession().getAttribute(TOOL_CONTENT_ID);
	if (strToolContentID == null) {
	    /*
	     * it is possible that the original request for authoring module is coming from monitoring url which keeps
	     * the TOOL_CONTENT_ID in the session
	     */
	    //strToolContentID is null, handle this

	    Long toolContentID = (Long) request.getSession().getAttribute(QaAppConstants.TOOL_CONTENT_ID);
	    if (toolContentID != null) {
		strToolContentID = toolContentID.toString();
	    } else {
		//we should IDEALLY not arrive here. The TOOL_CONTENT_ID is NOT available from the url or the session
		/* use default content instead of giving a warning */
		defaultContentId = qaAuthoringForm.getDefaultContentIdStr();
		strToolContentID = defaultContentId;
	    }
	}

	if (strToolContentID == null || strToolContentID.equals("")) {
	    QaUtils.cleanUpSessionAbsolute(request);
	    return mapping.findForward(QaAppConstants.ERROR_LIST);
	}

	qaAuthoringForm.setToolContentID(strToolContentID);

	/*
	 * find out if the passed tool content id exists in the db present user either a first timer screen with default
	 * content data or fetch the existing content.
	 * 
	 * if the toolcontentid does not exist in the db, create the default Map, there is no need to check if the
	 * content is locked in this case. It is always unlocked since it is the default content.
	 */

	String defaultContentIdStr = null;
	QaContent qaContent = null;
	if (!existsContent(new Long(strToolContentID).longValue(), qaService)) {
	    /* fetch default content */
	    defaultContentIdStr = qaAuthoringForm.getDefaultContentIdStr();
	    qaContent = retrieveContent(request, mapping, qaAuthoringForm, new Long(
		    defaultContentIdStr).longValue(), true, qaService, qaGeneralAuthoringDTO, sessionMap);

	} else {
	    /* it is possible that the content is in use by learners. */
	    qaContent = qaService.getQa(new Long(strToolContentID).longValue());
	    
	    if (qaService.isStudentActivityOccurredGlobal(qaContent)) {
		QaUtils.cleanUpSessionAbsolute(request);
		
		//add error.content.inUse to ActionMessages.
		persistError(request, "error.content.inUse");
		return mapping.findForward(QaAppConstants.ERROR_LIST);
	    }
	    qaContent = retrieveContent(request, mapping, qaAuthoringForm, new Long(
		    strToolContentID).longValue(), false, qaService, qaGeneralAuthoringDTO, sessionMap);
	}

	SortedSet<QaCondition> conditionList = getQaConditionList(sessionMap);
	conditionList.clear();
	conditionList.addAll(qaContent.getConditions());
	
	qaGeneralAuthoringDTO.setAllowRichEditor(qaContent.isAllowRichEditor());
	qaAuthoringForm.setAllowRichEditor(qaContent.isAllowRichEditor());
	
	qaGeneralAuthoringDTO.setUseSelectLeaderToolOuput(qaContent.isUseSelectLeaderToolOuput());
	qaAuthoringForm.setUseSelectLeaderToolOuput(qaContent.isUseSelectLeaderToolOuput());
	
	sessionMap.put(QaAppConstants.ATTR_QA_AUTHORING_FORM, qaAuthoringForm);

	String destination = QaUtils.getDestination(sourceMcStarter, requestedModule);
	request.getSession().setAttribute(sessionMap.getSessionID(), sessionMap);

	request.setAttribute(QaAppConstants.QA_GENERAL_AUTHORING_DTO, qaGeneralAuthoringDTO);

	return mapping.findForward(destination);
    }

    /**
     * retrives the existing content information from the db and prepares the
     * data for presentation purposes. 
     * 
     * @param request
     * @param mapping
     * @param qaAuthoringForm
     * @param mapQuestionContent
     * @param toolContentID
     * @return ActionForward
     */
    protected QaContent retrieveContent(HttpServletRequest request, ActionMapping mapping,
	    QaAuthoringForm qaAuthoringForm, long toolContentID, boolean isDefaultContent,
	    IQaService qaService, QaGeneralAuthoringDTO qaGeneralAuthoringDTO, SessionMap sessionMap) {
	
	QaContent qaContent = qaService.getQa(toolContentID);
	if (isDefaultContent && qaContent.getConditions().isEmpty()) {
	    qaContent.getConditions().add(qaService.createDefaultComplexCondition(qaContent));
	}
	

	QaUtils.populateAuthoringDTO(request, qaContent, qaGeneralAuthoringDTO);

	qaAuthoringForm.setUsernameVisible(qaContent.isUsernameVisible() ? "1" : "0");
	qaAuthoringForm.setAllowRateAnswers(qaContent.isAllowRateAnswers() ? "1" : "0");
	qaAuthoringForm.setShowOtherAnswers(qaContent.isShowOtherAnswers() ? "1" : "0");
	qaAuthoringForm.setSynchInMonitor(qaContent.isSynchInMonitor() ? "1" : "0");
	qaAuthoringForm.setQuestionsSequenced(qaContent.isQuestionsSequenced() ? "1" : "0");
	qaAuthoringForm.setLockWhenFinished(qaContent.isLockWhenFinished() ? "1" : "0");

	qaGeneralAuthoringDTO.setReflect(qaContent.isReflect() ? "1" : "0");

	qaAuthoringForm.setReflect(qaContent.isReflect() ? "1" : "0");

	qaAuthoringForm.setReflectionSubject(qaContent.getReflectionSubject());
	qaGeneralAuthoringDTO.setReflectionSubject(qaContent.getReflectionSubject());

	qaGeneralAuthoringDTO.setIsDefineLater(new Boolean(qaContent.isDefineLater()).toString());

	qaGeneralAuthoringDTO.setActivityTitle(qaContent.getTitle());
	qaAuthoringForm.setTitle(qaContent.getTitle());

	qaGeneralAuthoringDTO.setActivityInstructions(qaContent.getInstructions());
	qaAuthoringForm.setInstructions(qaContent.getInstructions());

	sessionMap.put(QaAppConstants.ACTIVITY_TITLE_KEY, qaGeneralAuthoringDTO.getActivityTitle());
	sessionMap.put(QaAppConstants.ACTIVITY_INSTRUCTIONS_KEY, qaGeneralAuthoringDTO.getActivityInstructions());

	List<QaQuestionDTO> listQuestionContentDTO = new LinkedList();

	/*
	 * get the existing question content
	 */
	boolean isFirst = false;
	Iterator queIterator = qaContent.getQaQueContents().iterator();
	while (queIterator.hasNext()) {

	    QaQueContent qaQuestion = (QaQueContent) queIterator.next();
	    if (qaQuestion != null) {
		QaQuestionDTO qaQuestionDTO = new QaQuestionDTO(qaQuestion);
		listQuestionContentDTO.add(qaQuestionDTO);
		/**
		 * make the first entry the default(first) one for jsp
		 */
		if (isFirst) {
		    qaGeneralAuthoringDTO.setDefaultQuestionContent(qaQuestion.getQuestion());
		    isFirst = false;
		}
	    }
	}
	

	request.setAttribute(QaAppConstants.TOTAL_QUESTION_COUNT, new Integer(listQuestionContentDTO.size()));
	request.setAttribute(QaAppConstants.LIST_QUESTION_CONTENT_DTO, listQuestionContentDTO);
	sessionMap.put(QaAppConstants.LIST_QUESTION_CONTENT_DTO_KEY, listQuestionContentDTO);

	SortedSet<QaCondition> conditionSet = new TreeSet<QaCondition>(new TextSearchConditionComparator());
	for (QaCondition condition : qaContent.getConditions()) {
	    conditionSet.add(condition);
	    for (QaQuestionDTO dto : listQuestionContentDTO) {
		for (QaQueContent question : condition.getQuestions()) {
		    if (dto.getDisplayOrder().equals(String.valueOf(question.getDisplayOrder()))) {
			condition.temporaryQuestionDTOSet.add(dto);
		    }
		}
	    }
	}
	sessionMap.put(QaAppConstants.ATTR_CONDITION_SET, conditionSet);

	if (isDefaultContent) {
	    qaGeneralAuthoringDTO.setDefaultQuestionContent("Sample Question 1?");

	}

	qaAuthoringForm.resetUserAction();
	
	return qaContent;
    }

    /**
     * each tool has a signature. QA tool's signature is stored in MY_SIGNATURE.
     * The default tool content id and other depending content ids are obtained
     * in this method. if all the default content has been setup properly the
     * method persists DEFAULT_CONTENT_ID in the session.
     * 
     * @param request
     * @param mapping
     * @return ActionForward
     */
    public boolean readSignature(HttpServletRequest request, ActionMapping mapping, IQaService qaService,
	    QaGeneralAuthoringDTO qaGeneralAuthoringDTO, QaAuthoringForm qaAuthoringForm) {
	
	/*
	 * retrieve the default content id based on tool signature
	 */
	long defaultContentID = 0;
	try {
	    defaultContentID = qaService.getToolDefaultContentIdBySignature(QaAppConstants.MY_SIGNATURE);
	    if (defaultContentID == 0) {
		QaStarterAction.logger.debug("default content id has not been setup");
		return false;
	    }
	} catch (Exception e) {
	    QaStarterAction.logger.error("error getting the default content id: " + e.getMessage());
	    persistError(request, "error.defaultContent.notSetup");
	    return false;
	}

	/*
	 * retrieve uid of the content based on default content id determined above
	 */
	try {
	    //retrieve uid of the content based on default content id determined above
	    QaContent qaContent = qaService.getQa(defaultContentID);
	    if (qaContent == null) {
		QaStarterAction.logger.error("Exception occured: No default content");
		persistError(request, "error.defaultContent.notSetup");
		return false;
	    }
	    
	} catch (Exception e) {
	    QaStarterAction.logger.error("Exception occured: No default question content");
	    persistError(request, "error.defaultContent.notSetup");
	    return false;
	}

	qaGeneralAuthoringDTO.setDefaultContentIdStr(new Long(defaultContentID).toString());
	qaAuthoringForm.setDefaultContentIdStr(new Long(defaultContentID).toString());

	return true;
    }

    /**
     * existsContent(long toolContentID)
     * 
     * @param long
     *                toolContentID
     * @return boolean determine whether a specific toolContentID exists in the
     *         db
     */
    protected boolean existsContent(long toolContentID, IQaService qaService) {
	QaContent qaContent = qaService.getQa(toolContentID);
	if (qaContent == null) {
	    return false;
	}

	return true;
    }

    /**
     * bridges define later url request to authoring functionality
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @param qaService
     * @return
     * @throws IOException
     * @throws ServletException
     * @throws QaApplicationException
     */
    public ActionForward executeDefineLater(ActionMapping mapping, QaAuthoringForm qaAuthoringForm,
	    HttpServletRequest request, HttpServletResponse response, IQaService qaService) throws IOException,
	    ServletException, QaApplicationException {
	return execute(mapping, qaAuthoringForm, request, response);
    }

    /**
     * persists error messages to request scope
     * 
     * @param request
     * @param message
     */
    public void persistError(HttpServletRequest request, String message) {
	ActionMessages errors = new ActionMessages();
	errors.add(Globals.ERROR_KEY, new ActionMessage(message));
	saveErrors(request, errors);
    }

    private SortedSet<QaCondition> getQaConditionList(SessionMap sessionMap) {
	SortedSet<QaCondition> list = (SortedSet<QaCondition>) sessionMap.get(QaAppConstants.ATTR_CONDITION_SET);
	if (list == null) {
	    list = new TreeSet<QaCondition>(new TextSearchConditionComparator());
	    sessionMap.put(QaAppConstants.ATTR_CONDITION_SET, list);
	}
	return list;
    }
}
