
package org.lamsfoundation.lams.author.model.activity
{
	import mx.collections.ArrayCollection;
	
	import org.lamsfoundation.lams.author.model.learninglibrary.Tool;
	import org.lamsfoundation.lams.author.util.Constants;
	
	public class ToolActivity extends Activity {
		public var toolID:Number;
		public var toolContentID:Number;		//generated by the LAMS server, has to do a round trip to populate them	
		public var gradebookToolOutputDefinitionName:String;
		
		public var activityEvaluations:ArrayCollection;
		public var competenceMappings:ArrayCollection; 	// competences to which this activity is mapped
		
		public var useDefaultToolOutput:Boolean;
		
		[Bindable] public var tool:Tool;
		
		public var groupingEnabled:Boolean = true; // Non persistent, used for property inspector

		function ToolActivity(activityUIID:Number){
			super(activityUIID);
			this.activityTypeID = Constants.ACTIVITY_TYPE_TOOL;
		}
		
	}
}

