alter table tl_lamind10_attachment drop foreign key FK11A17B15DC510063;
alter table tl_lamind10_node drop foreign key FKD1D2AD74A92257B8;
alter table tl_lamind10_node drop foreign key FKD1D2AD749EF6C402;
alter table tl_lamind10_node drop foreign key FKD1D2AD743DCB66D2;
alter table tl_lamind10_node drop foreign key FKD1D2AD74231F48FA;
alter table tl_lamind10_request drop foreign key FK170F65DDA92257B8;
alter table tl_lamind10_request drop foreign key FK170F65DD9EF6C402;
alter table tl_lamind10_session drop foreign key FK4C10F5E4DC510063;
alter table tl_lamind10_user drop foreign key FKD1D5EB3DDC7A09A0;
drop table if exists tl_lamind10_attachment;
drop table if exists tl_lamind10_mindmap;
drop table if exists tl_lamind10_node;
drop table if exists tl_lamind10_request;
drop table if exists tl_lamind10_session;
drop table if exists tl_lamind10_user;
create table tl_lamind10_attachment (uid bigint not null auto_increment, file_version_id bigint, file_type varchar(255), file_name varchar(255), file_uuid bigint, create_date datetime, mindmap_uid bigint, primary key (uid));
create table tl_lamind10_mindmap (uid bigint not null auto_increment, create_date datetime, update_date datetime, submission_deadline datetime, create_by bigint, title varchar(255), instructions longtext, run_offline bit, lock_on_finished bit, multiuser_mode bit, online_instructions longtext, offline_instructions longtext, content_in_use bit, define_later bit, tool_content_id bigint, export_content varchar(255), reflect_on_activity bit, reflect_instructions varchar(255), primary key (uid));
create table tl_lamind10_node (node_id bigint not null auto_increment, unique_id bigint, parent_id bigint, node_text varchar(255), node_color varchar(255), session_id bigint, user_id bigint, mindmap_id bigint, primary key (node_id));
create table tl_lamind10_request (uid bigint not null auto_increment, unique_id bigint, global_id bigint, request_type integer, node_id bigint, node_child_id bigint, user_id bigint, mindmap_id bigint, primary key (uid));
create table tl_lamind10_session (uid bigint not null auto_increment, session_end_date datetime, session_start_date datetime, status integer, session_id bigint, session_name varchar(250), mindmap_uid bigint, primary key (uid));
create table tl_lamind10_user (uid bigint not null auto_increment, user_id bigint, last_name varchar(255), login_name varchar(255), first_name varchar(255), finishedActivity bit, mindmap_session_uid bigint, entry_uid bigint, primary key (uid));
alter table tl_lamind10_attachment add index FK11A17B15DC510063 (mindmap_uid), add constraint FK11A17B15DC510063 foreign key (mindmap_uid) references tl_lamind10_mindmap (uid);
alter table tl_lamind10_node add index FKD1D2AD74A92257B8 (mindmap_id), add constraint FKD1D2AD74A92257B8 foreign key (mindmap_id) references tl_lamind10_mindmap (uid);
alter table tl_lamind10_node add index FKD1D2AD749EF6C402 (user_id), add constraint FKD1D2AD749EF6C402 foreign key (user_id) references tl_lamind10_user (uid);
alter table tl_lamind10_node add index FKD1D2AD743DCB66D2 (session_id), add constraint FKD1D2AD743DCB66D2 foreign key (session_id) references tl_lamind10_session (uid);
alter table tl_lamind10_node add index FKD1D2AD74231F48FA (parent_id), add constraint FKD1D2AD74231F48FA foreign key (parent_id) references tl_lamind10_node (node_id);
alter table tl_lamind10_request add index FK170F65DDA92257B8 (mindmap_id), add constraint FK170F65DDA92257B8 foreign key (mindmap_id) references tl_lamind10_mindmap (uid);
alter table tl_lamind10_request add index FK170F65DD9EF6C402 (user_id), add constraint FK170F65DD9EF6C402 foreign key (user_id) references tl_lamind10_user (uid);
alter table tl_lamind10_session add index FK4C10F5E4DC510063 (mindmap_uid), add constraint FK4C10F5E4DC510063 foreign key (mindmap_uid) references tl_lamind10_mindmap (uid);
alter table tl_lamind10_user add index FKD1D5EB3DDC7A09A0 (mindmap_session_uid), add constraint FKD1D5EB3DDC7A09A0 foreign key (mindmap_session_uid) references tl_lamind10_session (uid);
