INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lamind10',
'mindmapService',
'Mindmap',
'Mindmap',
'mindmap',
'@tool_version@',
0,
2,
'tool/lamind10/learning/learning.do?mode=learner',
'tool/lamind10/learning/learning.do?mode=author',
'tool/lamind10/learning/learning.do?mode=teacher',
'tool/lamind10/authoring/authoring.do',
'tool/lamind10/monitoring/monitoring.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lamind10',
'org.lamsfoundation.lams.tool.mindmap.ApplicationResources',
NOW(),
NOW(),
1
)