INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lavote11',
'voteService',
'Voting',
'Voting',
'vote',
'@tool_version@',
0,
2,
'tool/lavote11/learning/start.do?mode=learner',
'tool/lavote11/learning/start.do?mode=author',
'tool/lavote11/learning/start.do?mode=teacher',
'tool/lavote11/authoring/start.do',
'tool/lavote11/monitoring/start.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lavote11',
'org.lamsfoundation.lams.tool.vote.ApplicationResources',
NOW(),
NOW(),
1
)