INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lakalt11',
'kalturaService',
'Kaltura',
'Kaltura',
'kaltura',
'@tool_version@',
0,
2,
'tool/lakalt11/learning.do?mode=learner',
'tool/lakalt11/learning.do?mode=author',
'tool/lakalt11/learning.do?mode=teacher',
'tool/lakalt11/authoring.do',
'tool/lakalt11/monitoring.do',
'NULL',
'org.lamsfoundation.lams.tool.kaltura.ApplicationResources',
NOW(),
NOW(),
1
)