SET FOREIGN_KEY_CHECKS=0;
drop table if exists tl_laasse10_assessment;
drop table if exists tl_laasse10_assessment_overall_feedback;
drop table if exists tl_laasse10_assessment_question;
drop table if exists tl_laasse10_assessment_result;
drop table if exists tl_laasse10_assessment_unit;
drop table if exists tl_laasse10_option_answer;
drop table if exists tl_laasse10_question_option;
drop table if exists tl_laasse10_question_reference;
drop table if exists tl_laasse10_question_result;
drop table if exists tl_laasse10_session;
drop table if exists tl_laasse10_user;
SET FOREIGN_KEY_CHECKS=1;