INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
admin_url,
supports_outputs
)
VALUES
(
'laasse10',
'laasseAssessmentService',
'Assessment',
'Assessment',
'assessment',
'@tool_version@',
0,
2,
'tool/laasse10/learning/start.do?mode=learner',
'tool/laasse10/learning/start.do?mode=author',
'tool/laasse10/learning/start.do?mode=teacher',
'tool/laasse10/authoring/start.do',
'tool/laasse10/monitoring/summary.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/laasse10',
'org.lamsfoundation.lams.tool.assessment.ApplicationResources',
NOW(),
NOW(),
'tool/laasse10/admin/start.do',
1
)