-- CVS ID: $Id$

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lachat11_user;
DROP TABLE IF EXISTS tl_lachat11_attachment;
DROP TABLE IF EXISTS tl_lachat11_session;
DROP TABLE IF EXISTS tl_lachat11_chat;
SET FOREIGN_KEY_CHECKS=1;





