SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_lachat11_user;
DROP TABLE IF EXISTS tl_lachat11_message;
DROP TABLE IF EXISTS tl_lachat11_session;
DROP TABLE IF EXISTS tl_lachat11_chat;
DROP TABLE IF EXISTS tl_lachat11_conditions;
SET FOREIGN_KEY_CHECKS=1;