
 
INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
supports_run_offline_flag,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
define_later_url,
pedagogical_planner_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lachat11',
'chatService',
'Chat',
'Chat',
'chat',
'@tool_version@',
0,
2,
1,
'tool/lachat11/learning.do?mode=learner',
'tool/lachat11/learning.do?mode=author',
'tool/lachat11/learning.do?mode=teacher',
'tool/lachat11/authoring.do',
'tool/lachat11/monitoring.do',
'tool/lachat11/authoring.do?mode=teacher',
'tool/lachat11/pedagogicalPlanner.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lachat11',
'org.lamsfoundation.lams.tool.chat.ApplicationResources',
NOW(),
NOW(),
1
)
