SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_laqa11_conditions;
DROP TABLE IF EXISTS tl_laqa11_configuration;
DROP TABLE IF EXISTS tl_laqa11_usr_resp;
DROP TABLE IF EXISTS tl_laqa11_response_rating;
DROP TABLE IF EXISTS tl_laqa11_que_content;
DROP TABLE IF EXISTS tl_laqa11_que_usr;
DROP TABLE IF EXISTS tl_laqa11_session;
DROP TABLE IF EXISTS tl_laqa11_content;
DROP TABLE IF EXISTS tl_laqa11_condition_questions;
DROP TABLE IF EXISTS tl_laqa11_wizard_category;
DROP TABLE IF EXISTS tl_laqa11_wizard_cognitive_skill;
DROP TABLE IF EXISTS tl_laqa11_wizard_question;
SET FOREIGN_KEY_CHECKS=1;