SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS tl_labbb10_user;
DROP TABLE IF EXISTS tl_labbb10_config;
DROP TABLE IF EXISTS tl_labbb10_session;
DROP TABLE IF EXISTS tl_labbb10_bbb;
SET FOREIGN_KEY_CHECKS=1;