INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time,
supports_outputs
)
VALUES
(
'lalead11',
'leaderselectionService',
'Leaderselection',
'Leaderselection',
'leaderselection',
'@tool_version@',
0,
2,
'tool/lalead11/learning.do?mode=learner',
'tool/lalead11/learning.do?mode=author',
'tool/lalead11/learning.do?mode=teacher',
'tool/lalead11/authoring.do',
'tool/lalead11/monitoring.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/lalead11',
'org.lamsfoundation.lams.tool.leaderselection.ApplicationResources',
NOW(),
NOW(),
1
)