
package org.lamsfoundation.lams.author.model 
{
	class ToolActivity extends Activity {
		private var toolID:Number;
		private var toolContentID:Number;		//generated by the LAMS server, has to do a round trip to populate them	
		private var gradebookToolOutputDefinitionName:String;
		
		private var activityEvaluations:ArrayCollection;
		private var competenceMappings:ArrayCollection; 	// competences to which this activity is mapped
		
		private var useDefaultToolOutput:Boolean;
		
		function ToolActivity(){
		}
		

	}
}

