INSERT INTO lams_tool
(
tool_signature,
service_name,
tool_display_name,
description,
tool_identifier,
tool_version,
valid_flag,
grouping_support_type_id,
learner_url,
learner_preview_url,
learner_progress_url,
author_url,
monitor_url,
help_url,
language_file,
create_date_time,
modified_date_time
)
VALUES
(
'laprev11',
'peerreviewService',
'Peerreview',
'Peerreview',
'peerreview',
'@tool_version@',
0,
2,
'tool/laprev11/learning/start.do?mode=learner',
'tool/laprev11/learning/start.do?mode=author',
'tool/laprev11/learning/start.do?mode=teacher',
'tool/laprev11/authoring/start.do',
'tool/laprev11/monitoring/summary.do',
'http://wiki.lamsfoundation.org/display/lamsdocs/laprev11',
'org.lamsfoundation.lams.tool.peerreview.ApplicationResources',
NOW(),
NOW()
)