#!/bin/sh -e

. /usr/share/debconf/confmodule

# check if sysadmin pass has been answered, i.e. if we are updating existing install
db_get lams2/sysadmin_pass || true
sysadmin_pass="$RET"

db_input critical lams2/db_root_pass || true
#db_input critical lams2/db_name || true
#db_input critical lams2/db_user || true
#db_input critical lams2/db_pass || true
db_input critical lams2/server_host || true
db_input critical lams2/server_port || true
db_input critical lams2/sysadmin_user || true
db_input critical lams2/sysadmin_pass || true

# don't ask this q if updating (for updating from rc1 when this q was added)
if [ "x$sysadmin_pass" = "x" ] ; then
    db_input critical lams2/sysadmin_pass_confirm || true
else
    db_set lams2/sysadmin_pass_confirm $sysadmin_pass || true
fi

db_go

db_get lams2/sysadmin_pass || true
sysadmin_pass="$RET"
db_get lams2/sysadmin_pass_confirm || true
sysadmin_pass_confirm="$RET"

while [ "$sysadmin_pass" != "$sysadmin_pass_confirm" ]; do
    db_input critical lams2/sysadmin_pass_again || true
    db_input critical lams2/sysadmin_pass_confirm || true
    db_go
    db_get lams2/sysadmin_pass_again || true
    sysadmin_pass="$RET"
    db_get lams2/sysadmin_pass_confirm || true
    sysadmin_pass_confirm="$RET"
done
