activity.title = Survey
activity.description = Tool to create Surveys
activity.helptext = Answer surveys.
tool.display.name = Survey Tool
tool.description = Tool for survey.
label.authoring.heading = Survey Authoring
label.author.title = Survey
label.authoring.heading.basic = Basic
label.authoring.heading.advance = Advanced
label.authoring.heading.basic.desc = Basic input information for survey
label.authoring.heading.advance.desc = Please input advance options for survey
label.authoring.basic.title = Title
label.authoring.basic.instruction = Instructions
label.question = Question
label.optional = Optional
label.authoring.basic.add.survey.question = Add question
label.authoring.basic.add.survey.open.question = Add open-ended question
label.authoring.basic.add.option = Add more answers
label.authoring.basic.add.question = Save question
label.authoring.basic.question.optional = Optional question
label.authoring.basic.question.append.text = Allow 'Other' text entry
label.authoring.basic.question.allow.muli.answer = Allow multiple answers
label.authoring.basic.survey.list.title = Survey questions list
label.authoring.basic.survey = Survey
label.authoring.basic.survey.edit = Edit
label.authoring.basic.survey.delete = Delete
label.authoring.basic.survey.title.input = Title
label.authoring.advance.lock.on.finished = Lock when finished
label.authoring.advance.show.on.one.page = Show survey on one page
label.authoring.save.button = Save
label.authoring.cancel.button = Cancel
label.description = Description:
authoring.exception = There is a problem in survey authoring page, the reason is {0}
error.survey.item.question.blank = Question can not be blank
error.survey.item.question.less.option = You must input at least two options.
label.submit.survey = Done
label.retake.survey = Change answers
label.retake = [Change answer]
label.append.text = Append text:
label.next = Next
label.previous = Previous
label.of = of
error.upload.failed = Upload file failed: {0}
error.msg.default.content.not.find = Could not retrieve default content record for this tool.
error.mandatory.question = Mandatory question, please give answer.
authoring.msg.cancel.save = Do you want to close this window without saving?
label.learning.title = Survey Learning
label.learning.heading = Survey
label.resoruce.to.review = Survey to view
monitoring.tab.summary = Summary
monitoring.tab.statistics = Analytics
monitoring.tab.edit.activity = Edit activity
monitoring.label.group = Group
monitoring.summary.note = Note: number of students who have viewed the survey.
monitoring.label.type = Type
monitoring.label.title = Title
monitoring.label.number.learners = Number of students
monitoring.label.user.loginname = Login name
monitoring.label.user.name = Name
label.monitoring.edit.activity.cancel = Cancel
label.monitoring.edit.activity.update = Update
label.monitoring.edit.activity.edit = Edit
export.label.survey = Survey
error.title.empty = Title can not be blank
label.open = Open
label.delete = Delete
label.view = View
label.edit = Edit
label.finished = Next Activity
label.completed = Completed
label.finish = Next Activity
button.upload = Upload
button.add = Add
button.cancel = Cancel
message.monitoring.summary.no.session = No session available
label.show = Show
label.hide = Hide
label.save = Save
label.cancel = Cancel
monitoring.label.access.time = Access time
define.later.message = Please wait for the teacher to complete the content of this activity
message.monitoring.summary.no.survey.for.group = No survey available for this group.
button.try.again = Try again
label.up = Up
label.down = Down
label.monitoring.heading.access = Students list
label.authoring.advanced.reflectOnActivity = Add a notebook at end of Survey with the following instructions:
error.reflection.emtpy = Please input Notebook entry
title.reflection = Notebook entry
label.continue = Continue
monitoring.user.fullname = Name
monitoring.user.reflection = Notebook entry
page.title.monitoring.view.reflection = Notebook entries
button.close = Close
label.open.response = Open response
piechart.title = Question {0} Pie chart
barchart.title = Question {0} Column chart
barchart.category.axis.label = Candidate Answer
barchart.value.axis.label = Percentage
message.view.pie.chart = View pie chart
message.view.bar.chart = View column chart
message.possible.answers = Possible answers
message.total.user.response = Total user response
message.learner.choose.answer.percentage = {0} percent students of the class have chosen this answer.
message.learner.choose.answer = The student has chosen this answer
error.chart.gen = Error occurs during generating chart, please try again.
error.single.choice.over = Only one option or open text can be chosen.
title.chart.report = Report of individual question
label.answer = Answer
label.session.name = Session Name
label.number.learners = # of students
label.learner = Student
error.monitoring.export.excel = Export Survey report failed because of this reason: {0}
label.monitoring.button.export.excel = Export Report
errors.maxfilesize = The uploaded file has exceeded the maximum file size limit of {0} bytes
message.not.available = Not Available
message.warnLockOnFinish = Be aware: Once you finish this activity, when returning to it, you will no longer be able to add or make changes.
message.activityLocked = This activity has been set up by the teacher to prevent changes after its completion. While you can view your existing work upon returning, further additions are not permitted.
label.export.reflection = Notebook entries
label.on = On
label.off = Off
monitor.summary.th.advancedSettings = Advanced settings
monitor.summary.td.addNotebook = Add a notebook at the end of Survey
monitor.summary.td.notebookInstructions = Notebook instructions
label.authoring.advanced.notify.onanswersubmit = Notify instructors when a student submits an answer
event.answer.submit.subject = LAMS: A student submitted a survey answer in a Survey tool
event.answer.submit.body = The student {0} submitted a survey answer in a Survey tool.\n\nThis message was send automatically, following tool''s advanced settings.
label.specifyOther = Other - please specify
label.authoring.heading.conditions.desc = Please enter conditions for Survey
label.authoring.heading.conditions = Conditions
label.authoring.conditions.add.condition = Add condition
label.authoring.conditions.list.title = Conditions
label.authoring.conditions.order = Order
label.authoring.conditions.empty.condition.list = There are no conditions
label.authoring.conditions.condition.name = Name
error.condition.name.blank = Condition name can not be blank.
error.condition.duplicated.name = Duplicated name. Please choose unique one.
error.condition.no.questions.selected = There are no questions selected. Please select at least one.
error.condition = Error creating condition.
output.desc.text.search.output.definition.survey = Answers contain certain words
text.search.output.definition.survey.default.condition = First answer contains word "LAMS"
textsearch.heading = Answers that...
textsearch.all.words = have all these words:
textsearch.phrase = have this exact wording or phrase:
textsearch.any.words = have one or more of these words:
textsearch.excluded.words = have none of these unwanted words:
textsearch.questions = Search in these questions:
monitor.summary.date.restriction = Deadline
monitor.summary.when.date.restriction.is.set = After the specified date and time, students will be unable to access the activity.
monitor.summary.after.date = Date/time:
monitor.summary.set.restriction = Set restriction
monitor.summary.unset.restriction = Remove restriction
authoring.info.teacher.set.restriction = The instructor has set a deadline for this activity until {0}. Beyond this time, the activity will no longer be available.
monitor.summary.notification = Notification
monitor.summary.date.restriction.set = Date availability has been set
monitor.summary.date.restriction.removed = Date availability has been removed
label.copy = Copy
label.submit = Finish
label.monitoring.heading = Survey Monitoring
label.show.answers.from.other.users = Show answers from other students
label.view.all.responses = View all responses
label.sort.by.answer = Sort by answer
label.other.answers = Answers from other students
label.total.responses = Total responses so far: {0}
message.no.reflection.available = No notebook entry has been added.
label.search = Search...
label.answer.required = Answer required
label.survey.options = Options
label.activity.completion = End of Activity
label.notifications = Notifications
label.summary.downloaded = Report Downloaded
label.timestamp = Date/time:
outcome.authoring.title = Learning outcomes
outcome.authoring.input = Search and select by outcome name or code
outcome.authoring.existing = Added outcomes
outcome.authoring.existing.none = none
outcome.authoring.remove.confirm = Are you sure you want to remove this learning outcome?
outcome.authoring.create.new = [create new]
message.monitoring.edit.activity.not.editable = Activity cannot longer be edited
label.your.answers = Your answers
label.side.menu = Side menu
label.close.and.return = Close and return to the course
label.lams.logo = LAMS logo
label.support.activities = Support activities
label.my.progress = My progress
label.progress = Progress
label.skip.to.main.content = Skip to the main content
label.your.lesson.completion = Your lesson progression
label.your.portrait = Your profile portrait
label.lesson.name = Lesson name
label.activity.name = Activity name
label.confirm = Confirm
label.close = Close
label.click.to.open = Click to open
label.support.activity = Support activity
label.completed.activity = Activity completed
label.current.activity = Current activity
label.not.started.activity = Activity not reached yet
label.settings = Settings
label.refresh = Refresh
label.authoring.advance.anonymise.answers = Anonymise answers
label.authoring.advance.anonymise.answers.tooltip = \n When anonymised, student names will be replaced with fictional names. No real identifying information will be shown to you or anyone else reviewing the results. This setting cannot be undone after submission to protect student privacy.
label.new.feature = New
label.learning.anonymise.answers = This survey is anonymous – your real name will be replaced with a fictional one, and neither your classmates nor your lecturers will be able to identify you.
monitoring.summary.anonymise.answers = Student names have been replaced with fictitious ones to protect their identities as this survey is anonymised.
monitoring.learning.screen.anonymise.answers = This survey is anonymous. Answers from individual students are hidden.
label.monitoring.button.export.excel.all = Export all groups report
