SET FOREIGN_KEY_CHECKS=0;
drop table if exists tl_lascrt11_scratchie;
drop table if exists tl_lascrt11_scratchie_item;
drop table if exists tl_lascrt11_session;
drop table if exists tl_lascrt11_user;
drop table if exists tl_lascrt11_answer_log;
drop table if exists tl_lascrt11_burning_que_like;
drop table if exists tl_lascrt11_burning_question;
drop table if exists tl_lascrt11_configuration;
SET FOREIGN_KEY_CHECKS=1;